return {
    require 'plugin-config.which-key',
    'nvim-tree/nvim-web-devicons',
    require 'plugin-config.nvim-tree',
    require 'plugin-config.auto-save',
    require 'plugin-config.nvim-autopairs',
    require 'plugin-config.hop',
    require 'plugin-config.lazygit',
    require 'plugin-config.theme-melange',
    require 'plugin-config.barbecue',
    require 'plugin-config.lualine',
    require 'plugin-config.barbar',
--    require 'plugin-config.mini-animate',
    require 'plugin-config.lsconfig',
    require 'plugin-config.mason',
    require 'plugin-config.mason-lspconfig',
    require 'plugin-config.nvim-lspconfig',
    require 'plugin-config.telescope',
    require 'plugin-config.cmp',
    require 'plugin-config.rust-tools',


    require 'plugin-config.nvim-treesitter',
    require 'plugin-config.nvim-dap',
    require 'plugin-config.nvim-dap-ui',
    require 'plugin-config.fidget',
    require 'plugin-config.symbols-outline',
    require 'plugin-config.numb',
    require 'plugin-config.telescope-hop',
    require 'plugin-config.comment',
    require 'plugin-config.nvim-treesitter-context',
    require 'plugin-config.twilight',
}
